### ISSUE TITLE
Getting RuntimeException in Filesystem.php (line 55)

### ISSUE THREAD

**Issue by agarwa13** [nqxcode/laravel-lucene-search#15]
I think I am doing everything just fine but I must be doing something wrong or perhaps it is incompatible with something I don't recognize. I wrote a stackoverflow post describing in detail the steps I took. Here is the link to it: [http://stackoverflow.com/questions/32408994/laravel-5-1-laravel-lucene-search](http://stackoverflow.com/questions/32408994/laravel-5-1-laravel-lucene-search)

Here is an image of the error: 

![capture](https://cloud.githubusercontent.com/assets/4407018/9803761/ed40352e-57da-11e5-9c67-1be59b7b75c7.JPG)

Can you please help me if you know what it might be or if you have come across this error in your own testing.

**Comment by Cliffus** [comment]
are you sure that for the lucene-search directory, the correct owner and group are set? By using ls -l, you get an overview of files and directories in a given directory, together with their owner and group settings. Maybe compare the settings of lucene-search with the ones already working.

Updating these settings can be done with the chown command (chown -R user:group directory_name)

**Comment by agarwa13** [comment]
Now, I am super confused.

I ran `ls -l` and noticed that the lucene-search directory had root as owner and group.
so I ran `chown -R www-data:www-data lucene-search/` and it started working (sort of). The runtime exception went away but I get 0 results all the time.
So I ran `php artisan search:rebuild`
And the runtime error came back
I ran `ls -l` again and the user and group was www-data as expected
But I ran `chown -R www-data:www-data lucene-search/` again (gut feeling)
And the runtime error went away but of course I get 0 results again.

Any hints on what is going on?

**Comment by nqxcode** [comment]
Please 
1. run `chmod -R a+rw storage/app/lucene-search/`
2. run `php artisan search:rebuild -v`
3. show output for `ls -l  storage/app/lucene-search/index`

**Comment by agarwa13** [comment]
![capture](https://cloud.githubusercontent.com/assets/4407018/9893654/a05694b2-5bcf-11e5-8f8b-a2e9f8f45468.JPG)

Here you go. Apologies for the delayed reply. I was travelling.

**Comment by nqxcode** [comment]
Try run any query in tinker, for example:
`sudo php artisan tinker`
`> Search::query('significant')->count();`

What result?

**Comment by thxn** [comment]
I'm having the same exact issue. After trying the steps above, running the command in tinker still returns 0 results.

**Comment by cmoralesweb** [comment]
If you are logged as root, the commands you run are executed as root, tried this:

`su -c 'php artisan search:rebuild --verbose' www-data`
