### ISSUE TITLE
Add feature to change value of a Foreign key using Eloquent model.

### ISSUE THREAD

**Issue by imrealashu** [nqxcode/laravel-lucene-search#16]
For example:

table1
id = 1 (PK)
value = 'Something'

table2
id = 2
table1_id = 1
another_field='something else'

After Indexing `table2` result will be

id=2
table1_id='something'
another_field='something else'

**Comment by nqxcode** [comment]
In this example arise problem:
what field from `table1` to add to index if `table1` have other fields, besides "value" field?

 Therefore for all related fields use indexing for "dynamic fields" (see in readme). For example:
1. In config.php for model of `table2` add following option:
```php
        'optional_attributes' => true
```

2. Add this accessor in model of `table2`
```php
        public function getOptionalAttributesAttribute()
        {
                return [
                        'table1_id' => "something",
                ];
        }
```
