### ISSUE TITLE
Restricting search to a set of models?

### ISSUE THREAD

**Issue by mseymour** [nqxcode/laravel-lucene-search#28]
Is it possible to restrict queries to a single model or set of models?

**Comment by nqxcode** [comment]
Please, describe your trouble in detail.

**Comment by mseymour** [comment]
Let's say that I have `ModelA` and `ModelB`. I want to search for "Foo", but only in `ModelA`, not in both models.

**Comment by nqxcode** [comment]
Unfortunately, you can't make it. But you can filter results by model class.

**Comment by benhanks040888** [comment]
any example on this?

**Comment by nqxcode** [comment]
Added search method to `SearchTrait` that filter results by model class.
