### ISSUE TITLE
Persian/Arabic issue

### ISSUE THREAD

**Issue by mostafaznv** [nqxcode/laravel-lucene-search#34]
hi.
thanks for your nice package...
everything looks good, but i think it doesn't work with persian/arabic languages...
when i input a persian query, it return all rows ...
but it work nice with english

**Comment by mostafaznv** [comment]
i think i fixed it with below steps:

- remove `filters` from config 
- rebuild search tables

**Comment by nqxcode** [comment]
There is no stemming support for those languages, by default stemming only for english and russian languages is used.
