### ISSUE TITLE
Soft Reindex Database

### ISSUE THREAD

**Issue by pvanhemmen** [nqxcode/laravel-lucene-search#37]
Hey there,

Rebuild of the database via console always triggers a `search:clear` before reindexing. Wouldn't it be possible to make that optional, since every update executed calls `$this->delete($model)` in `Search.php` anyway? This way it would be possible to soft rebuild the database instead of clearing it right away. Or does this have any negative side effects?

The reason I ask is that I'm not able to use the `update / delete` events provided by the `SearchTrait`, since all my data is directly written to the database by an import. Rebuilding the index from scratch every time takes a lot of time, during which the search is not available.

Thanx for an awesome laravel extension and your support!

**Comment by nqxcode** [comment]
If you are about "performing of operations without indexing" like this https://mattstauffer.co/blog/introdtucing-laravel-scout#perform-operations-without-indexing, I will add this functionality in the near future.

**Comment by nqxcode** [comment]
Added performing of operations without indexing for models with ``SearchTrait``. Sorry for lay about "near future")
