### ISSUE TITLE
Support for Laravel 5.3?

### ISSUE THREAD

**Issue by Kovah** [nqxcode/laravel-lucene-search#38]
Hello!
Thank you for this fantastic package. Is support for Laravel 5.3 planned? I will test this locally but I doubt that there will be any breaking changes.

**Comment by nqxcode** [comment]
In the near future I didn't plan to port it, but I will be glad to accept any help with completion of a package. I'll release the new version of the package if there is a pool request with porting to Laravel 5.3.

**Comment by Aurlin** [comment]
I send a PR (#39).

**Comment by Kovah** [comment]
@nqxcode Could you please file a new release for version 2.3? The version is not available via composer at the moment. :(

**Comment by nqxcode** [comment]
Ok, use 2.3.x.x version for Laravel 5.3.
