### ISSUE TITLE
Call to undefined method Nqxcode\LuceneSearch\Search::where()

### ISSUE THREAD

**Issue by nkusibojoski** [nqxcode/laravel-lucene-search#41]
I have done all as it is described in the usage of this package, run the command 
"php artisan search:rebuild --verbose" , but when I try to get some results from the search I got this error 
"Call to undefined method Nqxcode\LuceneSearch\Search::where()" . 
I am using Laravel 5.2

Here is the code in my controller :
       $query = Search::where('name', 'clock');
        $models = $query->get();
        dd($models);
And here is the index : 
'index' => [
        'path' => storage_path('app') . '/lucene-search/index',

        'models' => [
            // Add models descriptions here.
            App\Models\Pet::class => [
                'fields' => [
                    'name', 'short_description', // fields for indexing
                ],
                'boost' => true
            ],
            App\Models\Breed::class => [
                'fields' => [
                    'name' // fields for indexing
                ],                
                'boost' => true
            ],
        ],
    ],

**Comment by nqxcode** [comment]
You should use \Search::where(), but not Nqxcode\LuceneSearch\Search::where().

**Comment by nkusibojoski** [comment]
Thanks a lot, it worked !
