### ISSUE TITLE
5.4 support

### ISSUE THREAD

**Issue by BlitZ-UK** [nqxcode/laravel-lucene-search#47]
Hey, great plugin! Is there any chance that this could be ported to work with 5.4? I get alot of composer errors when trying to install on Laravel 5.4

`Problem 1`
`- Installation request for nqxcode/laravel-lucene-search v2.3.0.3 -> satisfiable by nqxcode/laravel-lucene-search[v2.3.0.3].`
`- Conclusion: remove laravel/framework v5.4.19`
`- Conclusion: don't install laravel/framework v5.4.19`
`- nqxcode/laravel-lucene-search v2.3.0.3 requires illuminate/support 5.3.* -> satisfiable by illuminate/support[v5.3.0, v5.3.16, v5.3.23, v5.3.4].`
`- don't install illuminate/support v5.3.0|don't install laravel/framework v5.4.19`
`- don't install illuminate/support v5.3.16|don't install laravel/framework v5.4.19`
`- don't install illuminate/support v5.3.23|don't install laravel/framework v5.4.19`
`- don't install illuminate/support v5.3.4|don't install laravel/framework v5.4.19`
`- Installation request for laravel/framework == 5.4.19.0 -> satisfiable by laravel/framework[v5.4.19].`

Thanks!

**Comment by nqxcode** [comment]
Thnx! You can try to use v2.4.* for Laravel 5.4.

**Comment by odnan9** [comment]
Hi, 
I am having a lot of composer issues when trying to install with Laravel 5.5.*

  Problem 1
    - Conclusion: remove laravel/framework v5.5.40
    - Conclusion: don't install laravel/framework v5.5.40
    - Conclusion: don't install laravel/framework v5.5.39
    - Conclusion: don't install laravel/framework v5.5.38
    - Conclusion: don't install laravel/framework v5.5.37
    - Conclusion: don't install laravel/framework v5.5.36
    - Conclusion: don't install laravel/framework v5.5.35
    - Conclusion: don't install laravel/framework v5.5.34
    - Conclusion: don't install laravel/framework v5.5.33
    - Conclusion: don't install laravel/framework v5.5.32
    - Conclusion: don't install laravel/framework v5.5.31
    - Conclusion: don't install laravel/framework v5.5.30
    - Conclusion: don't install laravel/framework v5.5.29
    - Conclusion: don't install laravel/framework v5.5.28
    - Conclusion: don't install laravel/framework v5.5.27
    - Conclusion: don't install laravel/framework v5.5.26
    - Conclusion: don't install laravel/framework v5.5.25
    - Conclusion: don't install laravel/framework v5.5.24
    - Conclusion: don't install laravel/framework v5.5.23
    - Conclusion: don't install laravel/framework v5.5.22
    - Conclusion: don't install laravel/framework v5.5.21
    - Conclusion: don't install laravel/framework v5.5.20
    - Conclusion: don't install laravel/framework v5.5.19
    - Conclusion: don't install laravel/framework v5.5.18
    - Conclusion: don't install laravel/framework v5.5.17
    - Conclusion: don't install laravel/framework v5.5.16
    - Conclusion: don't install laravel/framework v5.5.15
    - Conclusion: don't install laravel/framework v5.5.14
    - Conclusion: don't install laravel/framework v5.5.13
    - Conclusion: don't install laravel/framework v5.5.12
    - Conclusion: don't install laravel/framework v5.5.11
    - Conclusion: don't install laravel/framework v5.5.10
    - Conclusion: don't install laravel/framework v5.5.9
    - Conclusion: don't install laravel/framework v5.5.8
    - Conclusion: don't install laravel/framework v5.5.7
    - Conclusion: don't install laravel/framework v5.5.6
    - Conclusion: don't install laravel/framework v5.5.5
    - Conclusion: don't install laravel/framework v5.5.4
    - Conclusion: don't install laravel/framework v5.5.3
    - Conclusion: don't install laravel/framework v5.5.2
    - Conclusion: don't install laravel/framework v5.5.1
    - nqxcode/laravel-lucene-search v2.4.0.0 requires illuminate/support 5.4.* -> satisfiable by illuminate/support[v5.4.0, v5.4.13, v5.4.17, v5.4.19, v5.4.27, v5.4.36, v5.4.9].
    - nqxcode/laravel-lucene-search v2.4.1.0 requires illuminate/support 5.4.* -> satisfiable by illuminate/support[v5.4.0, v5.4.13, v5.4.17, v5.4.19, v5.4.27, v5.4.36, v5.4.9].
    - nqxcode/laravel-lucene-search v2.4.1.1 requires illuminate/support 5.4.* -> satisfiable by illuminate/support[v5.4.0, v5.4.13, v5.4.17, v5.4.19, v5.4.27, v5.4.36, v5.4.9].
    - don't install laravel/framework v5.5.0|don't install illuminate/support v5.4.0
    - don't install laravel/framework v5.5.0|don't install illuminate/support v5.4.13
    - don't install laravel/framework v5.5.0|don't install illuminate/support v5.4.17
    - don't install laravel/framework v5.5.0|don't install illuminate/support v5.4.19
    - don't install laravel/framework v5.5.0|don't install illuminate/support v5.4.27
    - don't install laravel/framework v5.5.0|don't install illuminate/support v5.4.36
    - don't install laravel/framework v5.5.0|don't install illuminate/support v5.4.9
    - Installation request for laravel/framework 5.5.* -> satisfiable by laravel/framework[v5.5.0, v5.5.1, v5.5.10, v5.5.11, v5.5.12, v5.5.13, v5.5.14, v5.5.15, v5.5.16, v5.5.17, v5.5.18, v5.5.19, v5.5.2, v5.5.20, v5.5.21, v5.5.22, v5.5.23, v5.5.24, v5.5.25, v5.5.26, v5.5.27, v5.5.28, v5.5.29, v5.5.3, v5.5.30, v5.5.31, v5.5.32, v5.5.33, v5.5.34, v5.5.35, v5.5.36, v5.5.37, v5.5.38, v5.5.39, v5.5.4, v5.5.40, v5.5.5, v5.5.6, v5.5.7, v5.5.8, v5.5.9].
    - Installation request for nqxcode/laravel-lucene-search 2.4.* -> satisfiable by nqxcode/laravel-lucene-search[v2.4.0.0, v2.4.1.0, v2.4.1.1].
