### ISSUE TITLE
Docs need to be updated due to changes in version 2.4.1.0

### ISSUE THREAD

**Issue by Kovah** [nqxcode/laravel-lucene-search#49]
I recently updated Lucene  Search to version `2.4.1.0` and noticed some changes in how the query building works. I firth thought that I somehow made some mistakes but it was just the order of the query() method that changed.
The new `search()` method for models should be documented too.

Anyway, everything works fine. Thanks for oyur awesome work! 👍

**Comment by nqxcode** [comment]
Oops, quite forgot about readme. Fixed.
