### ISSUE TITLE
Working very slow with mysql

### ISSUE THREAD

**Issue by msafayasar** [nqxcode/laravel-lucene-search#52]
I have a table with about 40.000 rows and searching only one column. And for every search it takes about 25seconds. I am using Lucene to find names similar to the input and get them with AJAX. When I look at the timing, I see that every request takes nearly 25seconds as TTFB and even after I increased memory of my server, the speed did not change. The question is "How can I increase the search speed?"

**Comment by nqxcode** [comment]
Too many unknowns to solve such a problem.
