### ISSUE TITLE
Working with relationship

### ISSUE THREAD

**Issue by visualight** [nqxcode/laravel-lucene-search#53]
I use the version 2.2.* of Lucene Search.
Some tables of my database have data in another table.

1. How i can make a search that return all data (relationship method). I try this but the data returned in collection not link the relational table : "users".

```
public static function searchableIds(){
    return self::where('status', 2)->where('active', 1)->with('users')->lists('id');
}
```

2. How can I do (with an example) a search on my "product" table with the table where my product type is stored (product_type: table)? What I want to do is search for example on the word: airplane (stored in my product_type: table) and that this search returns all data related from the "product" table ??

Thank you

**Comment by nqxcode** [comment]
For indexing of data from other tables, you should use indexing for optional fields (see https://github.com/nqxcode/laravel-lucene-search#indexing-of-dynamic-fields). For example,
in product model add accessor like this:
 
public function getOptionalAttributesAttribute()
{
    $typesAttributes = [];
    foreach($this->types as $type) {
        $typesAttributes["type_{$type->id}"] = $type->name;
    }

    return $typeAttribute;
}
