### ISSUE TITLE
Add support for OR

### ISSUE THREAD

**Issue by cmoralesweb** [nqxcode/laravel-lucene-search#9]
Some of my models have translated fields, like so:

``` 
'title-es',
'title-en',
'text-es',
'text-en'
```

I put them all on the index config, but I want the search to be language-dependent (if the user has Spanish selected, only results matching ```title-es```  /  ```text-es``` should appear, not the ones for -en

```where()```accepts a single field, and if you combine a couple of ```where()``` the query runs with ```AND```. I'd need a ```OR``` in my case. 

... or perhaps there's another way that I'm missing :smile:

**Comment by nqxcode** [comment]
You use 'query builder' to make query and 'query builder' has no ```orWhere``` method yet.
But you can use raw queries (Lucene queries) without using the 'query builder'.

For example: ```Search::rawQuery('field1:"value1" OR field2:"value"');```

**Comment by cmoralesweb** [comment]
OK! :+1: 

```orWhere()``` would be a nice addition to the query builder, then.

**Comment by nqxcode** [comment]
Search by name OR description: ```Search::where(['name', 'description'], 'clock');`
